version: "3.9"


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1


volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}


services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      default:
        ipv4_address: 172.21.0.3
    restart: unless-stopped

  loki:
    image: grafana/loki:2.3.0
    volumes:
      - ./data/loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./data/loki/data:/data/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      default:
        ipv4_address: 172.21.0.4
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:

    volumes:
      - ./data/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      default:
        ipv4_address: 172.21.0.5
    restart: unless-stopped

  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      default:
        ipv4_address: 172.21.0.6
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./data/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      default:
        ipv4_address: 172.21.0.7
    restart: unless-stopped
